export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

//ADMIN
export const ALL_PRODUCT_REQUEST_ADMIN = "ALL_PRODUCT_REQUEST_ADMIN";
export const ALL_PRODUCT_SUCCESS_ADMIN = "ALL_PRODUCT_SUCCESS_ADMIN";
export const ALL_PRODUCT_FAIL_ADMIN = "ALL_PRODUCT_FAIL_ADMIN";

//clear errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";
